### ISSUE TITLE
GLFW build failed for no `make` target "install" on Ubuntu 18.04

### ISSUE THREAD

**Issue by chengchingwen** [JuliaGL/GLFW.jl#180]
I try install build GLFW and get the error complain about `make` has no target named "install"

```
 Error: Error building `GLFW`:
│ make: *** No rule to make target 'install'.  Stop.
│ [ Info: Attempting to create directory /home/peter/.julia/packages/GLFW/69NQ7/deps/downloads
│ [ Info: Directory /home/peter/.julia/packages/GLFW/69NQ7/deps/downloads already exists
│ [ Info: Downloading file https://github.com/glfw/glfw/archive/3.2.1.tar.gz
│ [ Info: Done downloading file https://github.com/glfw/glfw/archive/3.2.1.tar.gz
│ [ Info: Attempting to create directory /home/peter/.julia/packages/GLFW/69NQ7/deps/src
│ [ Info: Directory /home/peter/.julia/packages/GLFW/69NQ7/deps/src already exists
│ [ Info: Attempting to create directory /home/peter/.julia/packages/GLFW/69NQ7/deps
│ [ Info: Directory /home/peter/.julia/packages/GLFW/69NQ7/deps already exists
│ [ Info: Path /home/peter/.julia/packages/GLFW/69NQ7/deps/src/glfw-3.2.1 already exists
│ [ Info: Attempting to create directory /home/peter/.julia/packages/GLFW/69NQ7/deps/builds/glfw
│ [ Info: Directory /home/peter/.julia/packages/GLFW/69NQ7/deps/builds/glfw already exists
│ [ Info: Changing directory to /home/peter/.julia/packages/GLFW/69NQ7/deps/builds/glfw
│ [ Info: Changing directory to /home/peter/.julia/packages/GLFW/69NQ7/deps/builds/glfw
│ ERROR: LoadError: failed process: Process(setenv(`/home/peter/.julia/packages/CMake/ZGawK/deps/usr/bin/cmake --build . --target install`,["PATH=/home/peter/.julia/packages/GLFW/69NQ7/deps/usr/bin:/usr/local/cu
da-9.2/bin:/usr/local/cuda-9.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", "TEXTDOMAIN=im-config", "DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
", "QT_ACCESSIBILITY=1", "LD_LIBRARY_PATH=/home/peter/intel/compilers_and_libraries_2019.0.117/linux/mkl/lib/intel64:/home/peter/intel/compilers_and_libraries_2019.0.117/linux/mkl/lib/ia32:/usr/local/cuda/extras
/CUPTI/lib64:/usr/local/cuda-9.2/lib64:/home/peter/intel/compilers_and_libraries_2019.0.117/linux/mkl/lib/intel64:/home/peter/intel/compilers_and_libraries_2019.0.117/linux/mkl/lib/ia32:/usr/local/cuda/extras/CU
PTI/lib64:/usr/local/cuda-9.2/lib64", "MKL_INTERFACE_LAYER=ILP64", "TMUX=/tmp/tmux-1000/default,2011,28", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "XDG_SESSION_DESKTOP=ubuntu", "SSH_AGENT_PID=146
4", "XDG_SESSION_TYPE=x11", "USER=peter", "QT_IM_MODULE=ibus", "LESSCLOSE=/usr/bin/lesspipe %s %s", "XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg", "GNOME_SHELL_SESSION_MODE=ubuntu", "USERNAME=peter", "GDMSESSIO
N=ubuntu", "CLUTTER_IM_MODULE=xim", "DESKTOP_AUTOSTART_ID=10cb7ff0fe8cdfb4c315525930368946400000013680007", "XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop", "LESSOPEN=| /usr/
bin/lesspipe %s", "SHELL=/bin/bash", "COLORFGBG=default;default", "XDG_SEAT=seat0", "XAUTHORITY=/run/user/1000/gdm/Xauthority", "XDG_MENU_PREFIX=gnome-", "GTK_MODULES=gail:atk-bridge", "GTK_IM_MODULE=ibus", "SES
SION_MANAGER=local/peterserver:@/tmp/.ICE-unix/1368,unix/peterserver:/tmp/.ICE-unix/1368", "XMODIFIERS=@im=ibus", "MLTERM=3.8.4", "TMUX_PANE=%93", "HOME=/home/peter", "TERM=screen-256color", "S_COLORS=auto", "IM
_CONFIG_PHASE=2", "XDG_CURRENT_DESKTOP=ubuntu:GNOME", "LANG=zh_TW.UTF-8", "SHLVL=2", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "LOGNAME=peter", "XDG_RUNTIME_DIR=/run/user/1000", "SSH_AUTH_SOCK=/run/user/100
0/keyring/ssh", "DESKTOP_SESSION=ubuntu", "OLDPWD=/home/peter", "_=/home/peter/peter/julia/julia", "GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1", "GIO_LAUNCHED_DESKTOP_FILE=/etc/xdg/autostart/org.gnome.S
ettingsDaemon.MediaKeys.desktop", "PWD=/home/peter/peter/repo/100DaysAlgo.jl", "DISPLAY=:1", "OPENBLAS_NUM_THREADS=8", "LANGUAGE=zh_TW:zh", "XDG_VTNR=2", "WINDOWID=37748754", "MANDATORY_PATH=/usr/share/gconf/ubu
ntu.mandatory.path", "XDG_SESSION_ID=3", "TEXTDOMAINDIR=/usr/share/locale/", "JULIA_LOAD_PATH=@:/tmp/tmpA4AaIx", "GIO_LAUNCHED_DESKTOP_FILE_PID=1681", "QT4_IM_MODULE=xim", "WINDOWPATH=2", "LS_COLORS=rs=0:di=01;3
4:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.
lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tz
st=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31
:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.x
pm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v
=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.e
mf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;
36:*.xspf=00;36:", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(2)) [2]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
│  [2] pipeline_error at ./process.jl:785 [inlined]
│  [3] #run#515(::Bool, ::Function, ::Cmd) at ./process.jl:726
│  [4] run(::Cmd) at ./process.jl:724
│  [5] run(::BinDeps.SynchronousStepCollection) at /home/peter/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:521
│  [6] run(::FileRule) at /home/peter/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:483
│  [7] run(::BinDeps.SynchronousStepCollection) at /home/peter/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:521 (repeats 2 times)
│  [8] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at /home/peter/.julia/packages/BinDeps/ZEval/src/dependencies.jl:944
│  [9] satisfy!(::BinDeps.LibraryDependency) at /home/peter/.julia/packages/BinDeps/ZEval/src/dependencies.jl:922
│  [10] top-level scope at /home/peter/.julia/packages/BinDeps/ZEval/src/dependencies.jl:977
│  [11] include at ./boot.jl:326 [inlined]                                        
│  [12] include_relative(::Module, ::String) at ./loading.jl:1038                      
│  [13] include(::Module, ::String) at ./sysimg.jl:29                          
│  [14] include(::String) at ./client.jl:403                                
│  [15] top-level scope at none:0                                          
│ in expression starting at /home/peter/.julia/packages/GLFW/69NQ7/deps/build.jl:46
└ @ Pkg.Operations ~/peter/julia/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075
```

the `versioninfo()`
```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by Evizero** [comment]
experiencing the same issue

**Comment by mstobb** [comment]
Same here.  All suggestions appreciated.

**Comment by jarvist** [comment]
Same issue on Ubuntu 16.04. 
I managed to fix it, by building the dependency by hand. If you look at the error messages and inspect the log directory, `cmake` has failed to create the `Makefile` which then results in the 'make has no target named install'. 

Carrying out these build steps by hand in a terminal, then building the package again from within Julia (once the shared object file is in place) seems to work. 

I think Ubuntu has some weirdness with environment variables for X not being set in non-interactive shells? 

```
sudo apt-get install xorg-dev libglu1-mesa-dev
cd /home/jarvist/.julia/packages/GLFW/69NQ7/deps/builds/glfw
cmake ./
make install
```
Hope this helps!

**Comment by SimonDanisch** [comment]
I think this should be fixed with the new `build.jl`!

**Comment by schlichtanders** [comment]
still fails on fresh kubuntu 18.04, julia 1.1.0, `add Makie`, `] build GLMakie`

**Comment by SimonDanisch** [comment]
The fix isn't actually tagged, so you need to add `]ad GLFW#master`
